# =========================
# Application Configuration
# =========================

spring.application.name=notification-service
server.port = 8084

# =========================
# Database Configuration
# =========================

spring.datasource.url=jdbc:postgresql://localhost:5432/paypal
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# =========================
# JWT Configuration
# =========================

jwt.secret=mysupersecuresecretkeythatisatleast32characterising
jwt.expiration=86400000

# =========================
# External Service Configuration
# =========================

user.service.url=http://localhost:8081

# =========================
# Kafka Configuration
# =========================

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.properties.enable.idempotence=true

spring.kafka.consumer.group-id=transfer-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

kafka.topic.transfer.notification=transfer.notification
kafka.topic.deposit.notification=deposit.notification

# =========================
# Email Configuration
# =========================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=***********
spring.mail.password=***********

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

