# =========================
# Application Configuration
# =========================

spring.application.name=api-gateway
server.port=8080


# =========================
# JWT Configuration
# =========================

jwt.secret=mysupersecuresecretkeythatisatleast32characterising
jwt.expiration=86400000


# =========================
# Redis Configuration
# =========================

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000


# =========================
# Security Configuration
# =========================

# Public endpoints (NO AUTH REQUIRED)
app.security.public-paths=/api/users/signup,/api/users/login

# Internal APIs (BLOCKED FROM EXTERNAL ACCESS)
app.security.internal-paths=/api/wallets/create


# =========================
# Gateway Routes Configuration
# =========================

# ---------------------------------
# User Service
# ---------------------------------

spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/users/**

# Rate Limiter
spring.cloud.gateway.server.webflux.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.redis-rate-limiter.burstCapacity=10
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.key-resolver=#{@userKeyResolver}


# ---------------------------------
# Transaction Service
# ---------------------------------

spring.cloud.gateway.server.webflux.routes[1].id=transaction-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/transactions/**

# Rate Limiter
spring.cloud.gateway.server.webflux.routes[1].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.redis-rate-limiter.replenishRate=10
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.redis-rate-limiter.burstCapacity=20
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.key-resolver=#{@userKeyResolver}


# ---------------------------------
# Wallet Service
# ---------------------------------

spring.cloud.gateway.server.webflux.routes[2].id=wallet-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/wallets/**

# Rate Limiter
spring.cloud.gateway.server.webflux.routes[2].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[2].filters[0].args.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.server.webflux.routes[2].filters[0].args.redis-rate-limiter.burstCapacity=10
spring.cloud.gateway.server.webflux.routes[2].filters[0].args.key-resolver=#{@userKeyResolver}


# ---------------------------------
# Notification Service
# ---------------------------------

spring.cloud.gateway.server.webflux.routes[3].id=notification-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/notifications/**

# Rate Limiter
spring.cloud.gateway.server.webflux.routes[3].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[3].filters[0].args.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.server.webflux.routes[3].filters[0].args.redis-rate-limiter.burstCapacity=10
spring.cloud.gateway.server.webflux.routes[3].filters[0].args.key-resolver=#{@userKeyResolver}


# ---------------------------------
# Reward Service
# ---------------------------------

spring.cloud.gateway.server.webflux.routes[4].id=reward-service
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8085
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/rewards/**

# Rate Limiter
spring.cloud.gateway.server.webflux.routes[4].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[4].filters[0].args.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.server.webflux.routes[4].filters[0].args.redis-rate-limiter.burstCapacity=10
spring.cloud.gateway.server.webflux.routes[4].filters[0].args.key-resolver=#{@userKeyResolver}


# =========================
# Gateway Logging
# =========================

logging.level.org.springframework.cloud.gateway=INFO
logging.level.reactor.netty.http.client=INFO
logging.level.com.paypal.api_gateway=INFO