# =========================
# Application Configuration
# =========================
spring.application.name=wallet-service
server.port = 8083


# =========================
# Database Configuration
# =========================

spring.datasource.url=jdbc:postgresql://localhost:5432/paypal
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


# =========================
# JWT Configuration
# =========================

jwt.secret=mysupersecuresecretkeythatisatleast32characterising
jwt.expiration=86400000


# =========================
# Kafka Configuration
# =========================

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=wallet-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

kafka.topic.transfer.initiated=transfer.initiated
kafka.topic.transfer.result=transfer.result

kafka.topic.deposit.initiated=deposit.initiated
kafka.topic.deposit.result=deposit.result